services:
  # === Приложение ===
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    image: goph-profile:latest
    command: [ "./server" ]
    ports:
      - "8080:8080"
    environment:
      - SERVER_CONFIG_PATH=/app/config/server-docker.yaml
      - OTEL_SERVICE_NAME=avatar-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_healthy
    restart: unless-stopped

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    image: goph-profile:latest
    command: [ "./worker" ]
    environment:
      - WORKER_CONFIG_PATH=/app/config/worker-docker.yaml
      - OTEL_SERVICE_NAME=avatar-worker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
      otel-collector:
        condition: service_healthy
    restart: unless-stopped

  # === Инфраструктура ===
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  kafka:
    container_name: kafka
    image: apache/kafka:4.0.0
    ports:
      - "29092:29092"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "13133:13133"
    command:
      - "--config=/etc/otel-collector-config.yml"
    volumes:
      - ./deploy/otel/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    depends_on:
      - loki
      - jaeger
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:13133' ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    command:
      - "-config.file=/etc/loki/local-config.yml"
    ports:
      - "3100:3100"
    volumes:
      - ./deploy/loki/loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./deploy/grafana/dashboards:/etc/grafana/dashboards:ro
      - ./deploy/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deploy/prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    ports:
      - '9090:9090'

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - '9100:9100'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./deploy/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - '9093:9093'
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'

volumes:
  postgres_data:
  minio_data:
  kafka_data:
  loki-data:
  grafana-data:

networks:
  default:
    driver: bridge
